services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env.development
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: database
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data: