version: '3'
services:
  db:
    image: mariadb:latest 
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: Password123
      MARIADB_DATABASE: database
    networks:
      - internal
    ports:
      - '3306:3306'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    networks:
      - internal
    depends_on:
      db:
        condition: service_started
    restart: on-failure
networks:     
  internal:
    driver: bridge