version: '3.1'
services:
  db:
    image: mariadb:latest 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: database
      MYSQL_PORT: 3306
    expose:
      - 3306
  app:
    #stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    network_mode: "host" 
    env_file:
      - ./.env.development
    depends_on:
      - db
    restart: always